import Koa from 'koa';
import { Application as FeathersApplication } from '@feathersjs/feathers';
import bodyParser from 'koa-bodyparser';
import cors from '@koa/cors';
import { Application } from './declarations';
export { Koa, bodyParser, cors };
export * from './authentication';
export * from './declarations';
export * from './handlers';
export * from './rest';
export declare function koa<S = any, C = any>(feathersApp?: FeathersApplication<S, C>, koaApp?: Koa): Application<S, C>;
